"""increase title and filename length

Revision ID: 039b14b9113f
Revises: f3e64189e096
Create Date: 2026-05-05 14:30:35.598975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '039b14b9113f'
down_revision = 'f3e64189e096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('methodichka', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1055),
               existing_nullable=False)
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1055),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('methodichka', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=1055),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=1055),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
